import glob
import io
import logging
import math
import os
import re
import tarfile
import tempfile
import types
import warnings
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Iterable

import dill
import numpy as np
import pandas as pd
from configargparse import ArgumentParser, Namespace
from fastprop.cli.predict import predict_fastprop
from fastprop.cli.train import train_fastprop
from joblib import effective_n_jobs
from lightning import pytorch as pl
from rdkit import Chem
from rdkit.Chem import Mol
from sklearn.base import BaseEstimator, ClassifierMixin, RegressorMixin, is_classifier
from sklearn.utils.multiclass import unique_labels
from sklearn.utils.validation import check_is_fitted

from optunaz.algorithms.side_info import binarise_side_info, process_side_info


@contextmanager
def suppress_logging(level=logging.CRITICAL):
    """Surpresses the output from ChemProp training/inference"""
    logger = logging.getLogger()
    previous_level = logger.level
    logger.setLevel(level)
    try:
        yield
    finally:
        logger.setLevel(previous_level)


def save_model_memory(model_dir):
    """Saves the model directory as a tarball in memory.

    The function expects the directory which the existing trained ChemProp
    model resides. The directory should contain the model files generated by
    the ChemProp workflow.

    The returned tarball (tarblob) is used to store the model in memory
    and used for later extraction to a new temporary directory"""

    tarblob = io.BytesIO()
    with tarfile.TarFile(mode="w", fileobj=tarblob) as tar:
        dirinfo = tarfile.TarInfo(model_dir)
        dirinfo.mode = 0o755
        dirinfo.type = tarfile.DIRTYPE
        tar.addfile(dirinfo, None)
        for dirpath, _, files in os.walk(model_dir):
            for file in files:
                file_path = os.path.join(dirpath, file)
                with open(file_path, "rb") as fh:
                    filedata = io.BytesIO(fh.read())
                    fileinfo = tarfile.TarInfo(str(file_path))
                    fileinfo.size = len(filedata.getbuffer())
                    tar.addfile(fileinfo, filedata)
    return tarblob


def extract_model_memory(tarblob, temp_dir, save_dir):
    """Extracts the model directory from a tarball in memory.

    The input args are the tarball (tarblob) containing the model files
    (from save_model_memory_) the new temp directory (we create a new one
    to ensure access to the model files across operating systems) and the
    save_dir (the original temp directory when the model was first trained)"""
    tarblob.seek(0)
    with tarfile.TarFile(mode="r", fileobj=tarblob) as tar:
        for member in tar.getmembers():
            member.name = os.path.relpath(member.name, save_dir)
            tar.extract(member, temp_dir)
    return


class BaseFastProp(BaseEstimator):
    """
    Base class for FastProp models with Scikit-learn-like functionality.

    This class provides a unified interface for FastProp models and is inherited
    by `FastPropRegressor` and `FastPropClassifier` to reduce code duplication.

    Attributes:
        fnn_layers (int): Number of feedforward layers.
        learning_rate (float): Learning rate for training.
        batch_size (int): Batch size for training.
        number_epochs (int): Number of training epochs.
        number_repeats (int): Number of repeats (base estimators in an ensemble).
        train_size (float): Proportion of data used for training.
        val_size (float): Proportion of data used for validation.
        test_size (float): Proportion of data used for testing.
        random_seed (int): Random seed for reproducibility.
        hidden_size (int): Size of hidden layers.
        patience (int): Early stopping patience.
    """

    def __init__(
        self,
        fnn_layers: int = 2,
        learning_rate: float = 0.0001,
        batch_size: int = 2048,
        number_epochs: int = 30,
        number_repeats: int = 1,
        train_size: float = 0.8,
        val_size: float = 0.15,
        test_size: float = 0.05,
        random_seed: int = 42,
        hidden_size: int = 1800,
        patience: int = 5,
    ):
        self.fnn_layers = fnn_layers
        self.learning_rate = learning_rate
        self.batch_size = batch_size
        self.number_epochs = number_epochs
        self.number_repeats = number_repeats
        self.train_size = train_size
        self.val_size = val_size
        self.test_size = test_size
        self.random_seed = random_seed
        self.hidden_size = hidden_size
        self.patience = patience

    def fit(self, X, y, sample_weight=None):
        """
        Fits the model to the given data using the FastProp train_fastprop function.

        It expects (array-like): Input features and y (array-like): Target labels.
        The sample_weight (array-like) is for compatability and has no effect.
        """
        X = np.array(X)
        y = np.array(y)

        self.X_ = X
        self.y_ = y
        self.sample_weight_ = sample_weight

        if is_classifier(self):
            self.classes_ = unique_labels(y).astype(np.uint8)
            y = y.astype(np.uint8)

        self.target_columns_ = list(map(str, range(len(y))))
        descriptor_columns_ = list(map(str, range(self.X_.shape[1])))

        with tempfile.TemporaryDirectory() as output_dir:
            self.output_dir_ = output_dir

            pd.DataFrame(self.y_, columns=["targets"]).to_csv(
                os.path.join(output_dir, "input_file.csv"), index_label="Index"
            )

            pd.DataFrame(self.X_, columns=descriptor_columns_).to_csv(
                os.path.join(output_dir, "precomputed.csv"), index_label="Index"
            )

            with suppress_logging():
                train_fastprop(
                    output_directory=Path(output_dir),
                    input_file=Path(os.path.join(output_dir, "input_file.csv")),
                    smiles_column="Index",
                    descriptor_set="all",  # Only for compatibility (we pass our own)
                    target_columns=["targets"],
                    enable_cache=False,  # Avoid nested caching
                    precomputed=Path(os.path.join(output_dir, "precomputed.csv")),
                    fnn_layers=self.fnn_layers,
                    hidden_size=self.hidden_size,
                    clamp_input=False,  # Not currently implemented
                    learning_rate=self.learning_rate,
                    batch_size=self.batch_size,
                    number_epochs=self.number_epochs,
                    number_repeats=self.number_repeats,
                    problem_type="binary" if is_classifier(self) else "regression",
                    train_size=self.train_size,
                    val_size=self.val_size,
                    test_size=self.test_size,
                    sampler="random",
                    random_seed=self.random_seed,
                    patience=self.patience,
                    standardize=False,
                    hopt=False,
                )
            self.model_ = save_model_memory(output_dir)
            self.checkpoint_dir_ = next(
                d for d in os.listdir(output_dir) if re.match(r"^fastprop_.*", d)
            )
        return self

    def predict_proba(self, X):
        """
        Predicts probabilities for the given input data using the predict_fastprop helper.

        This method checks if the model has been fitted and then processes the input data
        to predict probabilities for classification tasks or regression values for regression tasks.
        """
        check_is_fitted(self, ["model_"])
        X = np.array(X)

        with tempfile.TemporaryDirectory() as tmpdir:
            precomputed_path = os.path.join(tmpdir, "precomputed_descriptors.csv")
            preds_path = os.path.join(tmpdir, "preds.csv")

            extract_model_memory(self.model_, tmpdir, self.output_dir_)

            pd.DataFrame(X, columns=list(map(str, range(X.shape[1])))).to_csv(
                precomputed_path, index_label="Index"
            )

            predict_fastprop(
                checkpoints_dir=Path(f"{tmpdir}/{self.checkpoint_dir_}/checkpoints"),
                smiles_strings=range(len(X)),
                descriptor_set="all",  # Only for compatibility (we pass our own)
                standardize=False,
                smiles_file=None,
                precomputed_descriptors=Path(precomputed_path),
                output=preds_path,
            )

            preds = pd.read_csv(preds_path)[["task_0"]].values

        if is_classifier(self):
            yhats = np.zeros([len(preds), 2])
            yhats[:, 1] = preds.flatten()
            yhats[:, 0] = 1 - yhats[:, 1]
            return yhats
        else:
            return preds.flatten()

    def predict(self, X):
        """Predicts target values for the given input data.

        This method determines whether the model is a classifier or regressor and
        returns predictions accordingly. For classifiers, it returns binary predictions
        based on a threshold of 0.5. For regressors, it returns the predicted y-value &
        clips probabilistic predictions  to the range [0, 1] if target values are within range.
        """
        if is_classifier(self):
            return self.predict_proba(X)[:, 1] > 0.5

        predictions = self.predict_proba(X).flatten()
        # clip probabilistic predictions
        return (
            predictions.clip(0, 1)
            if 0 <= self.y_.min() <= 1 and 0 <= self.y_.max() <= 1
            else predictions
        )

    def predict_uncert(self, X):
        """Predicts uncertainty for the given input data.

        Computes uncertainty estimates for predictions using the standard deviation,
        if ensembles were used (via number_repeats > 1) during training.
        """
        check_is_fitted(self, ["model_"])
        X = np.array(X)

        with tempfile.TemporaryDirectory() as tmpdir:
            precomputed_path = os.path.join(tmpdir, "precomputed_descriptors.csv")
            preds_path = os.path.join(tmpdir, "preds.csv")

            extract_model_memory(self.model_, tmpdir, self.output_dir_)

            pd.DataFrame(X, columns=list(map(str, range(X.shape[1])))).to_csv(
                precomputed_path, index_label="Index"
            )

            predict_fastprop(
                checkpoints_dir=Path(f"{tmpdir}/{self.checkpoint_dir_}/checkpoints"),
                smiles_strings=range(len(X)),
                descriptor_set="all",  # Only for compatibility (we pass our own)
                standardize=False,
                smiles_file=None,
                precomputed_descriptors=Path(precomputed_path),
                output=preds_path,
            )

            preds = pd.read_csv(preds_path)[["task_0", "task_0_stdev"]].values

        return preds[:, 0], preds[:, 1]


class FastPropRegressor(RegressorMixin, BaseFastProp):
    def __init__(
        self,
        fnn_layers: int = 2,
        learning_rate: float = 0.0001,
        batch_size: int = 2048,
        number_epochs: int = 30,
        number_repeats: int = 1,
        train_size: float = 0.8,
        val_size: float = 0.15,
        test_size: float = 0.05,
        random_seed: int = 42,
        hidden_size: int = 1800,
        patience: int = 5,
    ):
        self.fnn_layers = fnn_layers
        self.learning_rate = learning_rate
        self.batch_size = batch_size
        self.number_epochs = number_epochs
        self.number_repeats = number_repeats
        self.train_size = train_size
        self.val_size = val_size
        self.test_size = test_size
        self.random_seed = random_seed
        self.hidden_size = hidden_size
        self.patience = patience

    def __str__(self):
        do_not_print = {
            "X_",
            "y_",
            "model_",
        }
        attributes = [
            f"{key}='{value}'"
            for key, value in self.__dict__.items()
            if key not in do_not_print
        ]
        return f"FastPropRegressor({', '.join(attributes)})"


class FastPropClassifier(ClassifierMixin, BaseFastProp):
    def __init__(
        self,
        fnn_layers: int = 2,
        learning_rate: float = 0.0001,
        batch_size: int = 2048,
        number_epochs: int = 30,
        number_repeats: int = 1,
        train_size: float = 0.8,
        val_size: float = 0.15,
        test_size: float = 0.05,
        random_seed: int = 42,
        hidden_size: int = 1800,
        patience: int = 5,
    ):
        self.fnn_layers = fnn_layers
        self.learning_rate = learning_rate
        self.batch_size = batch_size
        self.number_epochs = number_epochs
        self.number_repeats = number_repeats
        self.train_size = train_size
        self.val_size = val_size
        self.test_size = test_size
        self.random_seed = random_seed
        self.hidden_size = hidden_size
        self.patience = patience

    def __str__(self):
        do_not_print = {
            "X_",
            "y_",
            "model_",
        }
        attributes = [
            f"{key}='{value}'"
            for key, value in self.__dict__.items()
            if key not in do_not_print
        ]
        return f"FastPropClassifier({', '.join(attributes)})"
